[build]
  command = "gatsby build"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="YOUR FLOTIQ API KEY"
  SNIPCART_API_KEY="NTc2NzQxNjgtZjNiYy00MDUxLWFmNTAtZTAxM2Q4MTdkNDU4NjM4Njk5NTM5MDU3OTE5NjEw"
  GA_MEASUREMENT_ID="YOUR MEASUREMENT ID"
